name: Deploy to Git Branch

on:
  push:
    branches:
      - rama_staging

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar código
        uses: actions/checkout@v3

      - name: Instalar dependencias
        run: npm ci

      - name: Build estático
        run: npm run build
        env:
          NEXT_PUBLIC_CLOUDINARY_CLOUD_NAME: ${{ secrets.NEXT_PUBLIC_CLOUDINARY_CLOUD_NAME }}
          NEXT_PUBLIC_API_URL_DEV: ${{ secrets.NEXT_PUBLIC_API_URL_DEV }}
          NEXT_PUBLIC_API_URL_PROD: ${{ secrets.NEXT_PUBLIC_API_URL_PROD }}
          NEXT_PUBLIC_API_URL_WHATSAPP_DEV: ${{ secrets.NEXT_PUBLIC_API_URL_WHATSAPP_DEV }}
          NEXT_PUBLIC_API_URL_WHATSAPP_PROD: ${{ secrets.NEXT_PUBLIC_API_URL_WHATSAPP_PROD }}
          CLOUDINARY_API_KEY: ${{ secrets.CLOUDINARY_API_KEY }}
          CLOUDINARY_API_SECRET: ${{ secrets.CLOUDINARY_API_SECRET }}

      - name: Push a rama deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          token: ${{ secrets.PERSONAL_TOKEN }}
          branch: deploy-staging
          folder: out
          clean: true